#!/bin/bash

PROG=$1
LOG=$2
BATCHES_DIR=$3
NUM_BATCHES=$4
GROUP_SIZE=$5 #parallelism factor; should evenly divide NUM_BATCHES

if [[ $# -lt 4 ]]; then
    echo "./train_err PROG LOG BATCHES_DIR NUM_BATCHES GROUP_SIZE"
    exit
fi

# Calculate the per-batches training error of PROG, storing
# <num-correct> for each batch in LOG

let last=`expr $NUM_BATCHES / $GROUP_SIZE - 1`
let last_group=`expr $GROUP_SIZE - 1`
for i in `seq 0 $last`; do
    echo "Batch group $i"
    for j in `seq 0 $last_group`; do
	let batch_no=`expr $GROUP_SIZE \* $i + $j`
	echo "Batch $batch_no"
	$PROG <$BATCHES_DIR/batch_$batch_no 1>>$LOG &
    done
    wait
done
